name: fit_ai
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #CORE
  equatable: ^2.0.5
  get_it: ^7.6.4

  #STATE MANAGEMENT
  flutter_bloc: ^8.1.3

  #CONFIG
  easy_localization: ^3.0.3

  #UTILITY
  kartal: ^3.5.0
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  #NETWORK
  vexana: ^3.5.4

  #NAVIGATION
  auto_route: ^7.8.4

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  mockito: ^5.3.2
  bloc_test: ^9.1.5
  patrol: ^2.3.1

flutter:
  uses-material-design: true
